#!/usr/bin/env python3
"""
Generate the final Fig. 8 panels contributed by the two original notebooks.

Panels included
---------------
b : Human and sheep ChromHMM emission probabilities (E1-E9)
d : E1-E9 merged-deduplicated CRE-class composition
e : phyloP raincloud plot by CRE class
f : UpSet plot of nominal positive trait × tissue enrichment hits
g : sfCRE trait enrichment dot plot with tissue colors and system annotation

Panels a, c and h are not generated by the two source notebooks and are
therefore intentionally excluded.

All paths can be overridden with environment variables; see CONFIG below.
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path
from typing import Iterable

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib.gridspec import GridSpec
from matplotlib.patches import Patch, Rectangle
from scipy.stats import gaussian_kde, ttest_ind
from statsmodels.stats.multitest import multipletests



# =============================================================================
# Global style
# =============================================================================

plt.style.use("default")
mpl.rcParams.update(
    {
        "axes.facecolor": "white",
        "figure.facecolor": "white",
        "axes.grid": False,
        "savefig.facecolor": "white",
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "font.family": "DejaVu Sans",
    }
)


# =============================================================================
# CONFIG: paths are supplied by workflow.py from config/paths*.tsv
# =============================================================================

def required_path(name: str) -> Path:
    value = os.environ.get(name)
    # Use a non-existent sentinel so imports and --help remain available before
    # configuration; require_file() will fail clearly if a panel is requested.
    return Path(value) if value else Path("__MISSING_CONFIG__") / name


E1E9_WORKDIR = required_path("E1E9_WORKDIR")
FIG_DIR = Path(os.environ.get("FIG8_FINAL_DIR", E1E9_WORKDIR / "fig8_final_panels"))
MERGED_CLASSIFICATION = Path(
    os.environ.get(
        "MERGED_CLASSIFICATION",
        E1E9_WORKDIR
        / "visualization_tables_E1E9_reuse_existing"
        / "results_hg38"
        / "merged_classification_summary.tsv",
    )
)
CONSERVATION_TABLE = required_path("CONSERVATION_TABLE")
HUMAN_EMISSION = required_path("HUMAN_EMISSION")
SHEEP_EMISSION_R1 = required_path("SHEEP_EMISSION_R1")
SHEEP_EMISSION_R2 = required_path("SHEEP_EMISSION_R2")

GWAS_BASE = required_path("GWAS_BASE")
GWAS_STATS = Path(
    os.environ.get(
        "GWAS_STATS",
        str(GWAS_BASE / "summary" / "A2_B2_all_tissues_all_classes_enrichment_stats_long.csv"),
    )
)
TRAIT_38_XLSX = Path(
    os.environ.get(
        "TRAIT_38_XLSX",
        str(GWAS_BASE / "human_GWAS_38_Trait_new.xlsx"),
    )
)
TRAIT_152_TSV = Path(
    os.environ.get(
        "TRAIT_152_TSV",
        str(GWAS_BASE / "all_152_traits.tsv"),
    )
)
TISSUE_COLOR_FILE = Path(
    os.environ.get(
        "TISSUE_COLOR_FILE",
        str(GWAS_BASE / "tissue_color.txt"),
    )
)

ALLOW_OVERWRITE = False


# =============================================================================
# Shared constants
# =============================================================================

STATE_ORDER = [f"E{i}" for i in range(1, 10)]

STATE_LABELS = {
    "E1": "TssA",
    "E2": "TssFlnk",
    "E3": "TssWk",
    "E4": "TssBiv",
    "E5": "EnhA",
    "E6": "EnhAMe",
    "E7": "EnhAHet",
    "E8": "EnhPois",
    "E9": "Repr",
}

STATE_COLORS = {
    "E1": "#FF0000",
    "E2": "#FF2C79",
    "E3": "#F08080",
    "E4": "#FCE0E0",
    "E5": "#FFFF00",
    "E6": "#D6A32B",
    "E7": "#F0C36B",
    "E8": "#F5E1A1",
    "E9": "#B0B0B0",
}

CRE_ORDER = ["sfCRE", "sdCRE", "soCRE", "ssCRE"]
CRE_COLORS = {
    "sfCRE": "#BB5A3E",
    "sdCRE": "#CD8F7A",
    "soCRE": "#E1CFCB",
    "ssCRE": "#78ACC4",
}

TISSUE_ORDER = [
    "Cortex",
    "Spleen",
    "Heart",
    "Adipose",
    "Ovary",
    "Lung",
    "Colon",
    "Stomach",
    "Sintest",
    "Liver",
]

TISSUE_ALIAS = {
    "Cortex": "Cerebral_cortex",
    "Stomach": "Abomasum",
    "Sintest": "Small_Intestine",
    "Small intestine": "Small_Intestine",
}

TISSUE_DISPLAY = {
    "Cerebral_cortex": "Cerebral cortex",
    "Spleen": "Spleen",
    "Heart": "Heart",
    "Adipose": "Adipose",
    "Ovary": "Ovary",
    "Lung": "Lung",
    "Colon": "Colon",
    "Abomasum": "Abomasum",
    "Small_Intestine": "Small intestine",
    "Liver": "Liver",
}

SYSTEM_COLORS = {
    "nervous_system": "#6F67B1",
    "Immune_system": "#4FA262",
    "blood_biochemical_index": "#4C72B0",
    "cardiovascular_system": "#C44E52",
    "body_size": "#8C6D31",
    "reproductive": "#C34E8B",
    "metabolic_lipid": "#E39A2D",
    "blood_routine_examination": "#4EA3B7",
}

SYSTEM_DISPLAY = {
    "nervous_system": "Nervous system",
    "Immune_system": "Immune system",
    "blood_biochemical_index": "Blood biochemical index",
    "cardiovascular_system": "Cardiovascular system",
    "body_size": "Body size",
    "reproductive": "Reproductive",
    "metabolic_lipid": "Metabolic lipid",
    "blood_routine_examination": "Blood routine examination",
}

SYSTEM_ORDER = list(SYSTEM_DISPLAY)

# Full descriptions are used to impose the final order; Excel abbreviations are
# used as displayed labels.
TRAIT_DESCRIPTION_ORDER = [
    "Bipolar and major depression status",
    "Sleep duration",
    "Neuroticism score",
    "Age hay fever, rhinitis or eczema diagnosed",
    "Albumin/Globulin ratio",
    "serum non-albumin protein measurement",
    "Total bilirubin",
    "Direct bilirubin",
    "Hypertension",
    "Pulse rate",
    "ECG, heart rate",
    "Vascular/heart problems diagnosed by doctor",
    "Maximum heart rate during fitness test",
    "Birth weight",
    "Standing height",
    "Ankle spacing width",
    "waist-hip ratio",
    "Trunk fat-free mass",
    "Whole body fat-free mass",
    "Weight",
    "IGF-1",
    "N83 Noninflammatory disorders of ovary, Fallopian tube and broad ligament",
    "Oestradiol",
    "Testosterone",
    "Cholesterol",
    "hypercholesterolemia",
    "Apolipoprotein A",
    "Apolipoprotein B",
    "LDL direct",
    "Glucose",
    "Triglycerides",
    "Red blood cell (erythrocyte) distribution width",
    "Mean corpuscular haemoglobin",
]

# The final figure excludes asthma and three additional unwanted/duplicate traits.
DROP_TRAIT_IDS = {
    "categorical-6150-both_sexes-4",
    "categorical-20002-both_sexes-1065",
    "categorical-6150-both_sexes-100",
    "categorical-1777-both_sexes-1777",
    "categorical-20002-both_sexes-1473",
}


# =============================================================================
# Generic helpers
# =============================================================================

def require_file(path: Path) -> Path:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    return path


def save_panel(fig: mpl.figure.Figure, stem: str) -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    pdf = FIG_DIR / f"{stem}.pdf"
    png = FIG_DIR / f"{stem}.png"
    existing = [path for path in (pdf, png) if path.exists()]
    if existing and not ALLOW_OVERWRITE:
        raise FileExistsError(
            "Refusing to overwrite existing panel output(s): "
            + ", ".join(str(path) for path in existing)
        )
    fig.savefig(pdf, bbox_inches="tight")
    fig.savefig(png, dpi=300, bbox_inches="tight")
    print(f"saved: {pdf}")
    print(f"saved: {png}")


def norm_text(value: object) -> str:
    if pd.isna(value):
        return ""
    return re.sub(r"\s+", " ", str(value).strip().lower())


def tissue_color_key(tissue: str) -> str:
    return TISSUE_ALIAS.get(str(tissue), str(tissue))


def load_tissue_color_map(path: Path | None = None) -> dict[str, str]:
    path = TISSUE_COLOR_FILE if path is None else path
    table = pd.read_csv(require_file(path), sep=r"\s+", engine="python")
    table = table.rename(columns={table.columns[0]: "Tissue", table.columns[1]: "Color"})
    return dict(zip(table["Tissue"].astype(str), table["Color"].astype(str)))


# =============================================================================
# Panel b: emission probabilities
# =============================================================================

def _canonical_mark(mark: str) -> str:
    compact = re.sub(r"[^a-z0-9]", "", str(mark).lower())
    aliases = {
        "h3k27me3": "H3K27me3",
        "h3k4me1": "H3K4me1",
        "h3k27ac": "H3K27ac",
        "atac": "ATAC-seq",
        "atacseq": "ATAC-seq",
        "h3k4me3": "H3K4me3",
    }
    return aliases.get(compact, str(mark))


def load_emissions(path: Path) -> pd.DataFrame:
    df = pd.read_csv(require_file(path), sep="\t")
    df = df.rename(columns={df.columns[0]: "state"})
    df["state"] = [f"E{int(x)}" for x in df["state"]]
    df = df.set_index("state")
    df = df.rename(columns={c: _canonical_mark(c) for c in df.columns})
    return df


def plot_panel_b() -> None:
    human = load_emissions(HUMAN_EMISSION)
    sheep = (load_emissions(SHEEP_EMISSION_R1) + load_emissions(SHEEP_EMISSION_R2)) / 2

    mark_order = ["H3K27me3", "H3K4me1", "H3K27ac", "ATAC-seq", "H3K4me3"]
    common_marks = [m for m in mark_order if m in human.columns and m in sheep.columns]
    if not common_marks:
        raise ValueError("No expected histone/ATAC marks are shared by human and sheep tables.")

    human = human.reindex(index=STATE_ORDER, columns=common_marks)
    sheep = sheep.reindex(index=STATE_ORDER, columns=common_marks)

    fig = plt.figure(figsize=(5.1, 3.25))
    gs = GridSpec(
        1,
        5,
        figure=fig,
        width_ratios=[1.10, 0.38, 1.55, 1.55, 0.10],
        wspace=0.10,
    )

    ax_label = fig.add_subplot(gs[0, 0])
    ax_state = fig.add_subplot(gs[0, 1])
    ax_human = fig.add_subplot(gs[0, 2])
    ax_sheep = fig.add_subplot(gs[0, 3])
    cax = fig.add_subplot(gs[0, 4])

    # State semantic labels and colors.
    ax_label.set_xlim(0, 1)
    ax_label.set_ylim(len(STATE_ORDER), 0)
    for i, state in enumerate(STATE_ORDER):
        ax_label.add_patch(
            Rectangle((0, i), 1, 1, facecolor=STATE_COLORS[state], edgecolor="white", linewidth=0.4)
        )
        ax_label.text(
            0.5,
            i + 0.5,
            STATE_LABELS[state],
            ha="center",
            va="center",
            fontsize=8,
        )
    ax_label.axis("off")

    ax_state.set_xlim(0, 1)
    ax_state.set_ylim(len(STATE_ORDER), 0)
    for i, state in enumerate(STATE_ORDER):
        ax_state.text(0.5, i + 0.5, state, ha="center", va="center", fontsize=8)
    ax_state.axis("off")

    sns.heatmap(
        human,
        cmap="Reds",
        vmin=0,
        vmax=1,
        cbar=False,
        yticklabels=False,
        xticklabels=common_marks,
        ax=ax_human,
    )
    sns.heatmap(
        sheep,
        cmap="Reds",
        vmin=0,
        vmax=1,
        cbar=True,
        cbar_ax=cax,
        cbar_kws={"label": "Emission probability"},
        yticklabels=False,
        xticklabels=common_marks,
        ax=ax_sheep,
    )

    for ax, title in [(ax_human, "Human emission"), (ax_sheep, "Sheep emission")]:
        ax.set_title(title, fontsize=9, pad=5)
        ax.set_xlabel("Mark", fontsize=9)
        ax.set_ylabel("")
        ax.tick_params(axis="x", labelrotation=90, labelsize=7, length=0)
        for spine in ax.spines.values():
            spine.set_visible(False)

    cax.tick_params(labelsize=7)
    cax.set_ylabel("Emission probability", fontsize=8)

    save_panel(fig, "Fig8b_emission_E1_E9")
    plt.show()


# =============================================================================
# Panel d: merged-deduplicated composition
# =============================================================================

def plot_panel_d() -> None:
    df = pd.read_csv(require_file(MERGED_CLASSIFICATION), sep="\t")
    missing = {"state", "total", *CRE_ORDER} - set(df.columns)
    if missing:
        raise ValueError(f"Merged classification table is missing columns: {sorted(missing)}")

    df = df.set_index("state").reindex(STATE_ORDER)
    proportions = df[CRE_ORDER].div(df["total"].replace(0, np.nan), axis=0).fillna(0)

    fig, ax = plt.subplots(figsize=(3.65, 2.75))
    bottom = np.zeros(len(proportions))

    for cre in CRE_ORDER:
        values = proportions[cre].to_numpy()
        ax.bar(
            STATE_ORDER,
            values,
            bottom=bottom,
            width=0.78,
            color=CRE_COLORS[cre],
            edgecolor="white",
            linewidth=0.45,
            label=cre,
        )
        bottom += values

    ax.set_ylim(0, 1)
    ax.set_ylabel("Proportion")
    ax.set_xlabel("Human state")
    ax.set_title("E1-E9 merged-deduplicated classification composition", fontsize=8.5)
    ax.legend(
        frameon=False,
        fontsize=7,
        handlelength=1.0,
        handletextpad=0.35,
        borderaxespad=0.2,
        loc="upper left",
        bbox_to_anchor=(0.98, 1.01),
    )
    ax.tick_params(axis="both", labelsize=8)
    sns.despine(ax=ax)

    save_panel(fig, "Fig8d_E1_E9_merged_classification_composition")
    plt.show()


# =============================================================================
# Panel e: phyloP raincloud
# =============================================================================

def _p_to_star(qvalue: float) -> str:
    if qvalue < 1e-4:
        return "****"
    if qvalue < 1e-3:
        return "***"
    if qvalue < 1e-2:
        return "**"
    if qvalue < 0.05:
        return "*"
    return "ns"


def _add_pairwise_fdr_brackets_horizontal(
    ax: mpl.axes.Axes,
    groups: dict[str, np.ndarray],
    order: list[str],
) -> None:
    pairs: list[tuple[int, int]] = [
        (i, j) for i in range(len(order)) for j in range(i + 1, len(order))
    ]
    pairs.sort(key=lambda pair: (pair[1] - pair[0], pair[0]))

    pvalues = []
    valid_pairs = []
    for i, j in pairs:
        a = groups.get(order[i], np.array([]))
        b = groups.get(order[j], np.array([]))
        if len(a) < 2 or len(b) < 2:
            continue
        pvalues.append(ttest_ind(a, b, equal_var=False, nan_policy="omit").pvalue)
        valid_pairs.append((i, j))

    if not pvalues:
        return

    qvalues = multipletests(pvalues, method="fdr_bh")[1]
    significant = [
        (pair, q) for pair, q in zip(valid_pairs, qvalues) if np.isfinite(q) and q < 0.05
    ]
    if not significant:
        return

    x0, x1 = ax.get_xlim()
    xr = x1 - x0
    base_x = x1 + 0.04 * xr
    step_x = 0.055 * xr
    tick = 0.015 * xr

    for rank, ((i, j), qvalue) in enumerate(significant):
        x = base_x + rank * step_x
        ax.plot([x - tick, x], [i, i], color="black", lw=0.65, clip_on=False)
        ax.plot([x - tick, x], [j, j], color="black", lw=0.65, clip_on=False)
        ax.plot([x, x], [i, j], color="black", lw=0.65, clip_on=False)
        ax.text(
            x + 0.008 * xr,
            (i + j) / 2,
            _p_to_star(float(qvalue)),
            rotation=90,
            va="center",
            ha="left",
            fontsize=6,
            clip_on=False,
        )

    ax.set_xlim(x0, base_x + (len(significant) - 1) * step_x + 0.34 * xr)


def plot_panel_e() -> None:
    df = pd.read_csv(require_file(CONSERVATION_TABLE), sep="\t")
    required = {"cre_type", "phyloP_mean", "phyloP_covered_bp"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Conservation table is missing columns: {sorted(missing)}")

    plot_df = (
        df.loc[df["cre_type"].isin(CRE_ORDER)]
        .dropna(subset=["phyloP_mean"])
        .query("phyloP_covered_bp > 0")
        .copy()
    )

    all_values = plot_df["phyloP_mean"].replace([np.inf, -np.inf], np.nan).dropna()
    xmin, xmax = all_values.quantile([0.005, 0.995]).to_numpy()
    xpad = 0.06 * (xmax - xmin)
    xmin, xmax = xmin - xpad, xmax + xpad
    grid = np.linspace(xmin, xmax, 300)

    rng = np.random.default_rng(1)
    groups: dict[str, np.ndarray] = {}

    fig, ax = plt.subplots(figsize=(2.75, 3.45))

    for y, cre in enumerate(CRE_ORDER):
        values = (
            plot_df.loc[plot_df["cre_type"] == cre, "phyloP_mean"]
            .replace([np.inf, -np.inf], np.nan)
            .dropna()
            .to_numpy()
        )
        if len(values) == 0:
            continue
        groups[cre] = values

        kde_values = values
        if len(kde_values) > 50_000:
            kde_values = rng.choice(kde_values, 50_000, replace=False)

        if len(np.unique(kde_values)) > 2:
            density = gaussian_kde(kde_values)(grid)
            density = density / density.max() * 0.34
            ax.fill_between(
                grid,
                y,
                y + density,
                color=CRE_COLORS[cre],
                alpha=0.28,
                linewidth=0,
                zorder=1,
            )
            ax.plot(grid, y + density, color=CRE_COLORS[cre], lw=0.9, zorder=2)

        bp = ax.boxplot(
            values,
            positions=[y - 0.28],
            vert=False,
            widths=0.25,
            patch_artist=True,
            showfliers=False,
            manage_ticks=False,
            medianprops={"color": "black", "linewidth": 0.9},
            boxprops={"linewidth": 0.65},
            whiskerprops={"linewidth": 0.65},
            capprops={"linewidth": 0.65},
        )
        for patch in bp["boxes"]:
            patch.set_facecolor(mpl.colors.to_rgba(CRE_COLORS[cre], alpha=0.80))
            patch.set_edgecolor("black")

        ax.text(
            xmax + 0.07 * (xmax - xmin),
            y + 0.22,
            f"$n$ = {len(values):,}",
            fontsize=6.5,
            ha="left",
            va="center",
            clip_on=False,
        )

    ax.axvline(0, color="grey", lw=0.55, ls="--", zorder=0)
    ax.set_xlim(xmin, xmax)
    ax.set_yticks(range(len(CRE_ORDER)))
    ax.set_yticklabels(CRE_ORDER, fontsize=8)
    ax.set_ylim(-0.55, len(CRE_ORDER) - 0.22)
    ax.invert_yaxis()
    ax.set_title("phyloP", fontsize=9)
    ax.set_xlabel("Mean phyloP score per CRE", fontsize=8)
    ax.set_ylabel("CRE class", fontsize=8)
    ax.tick_params(axis="x", labelsize=7)
    sns.despine(ax=ax)

    _add_pairwise_fdr_brackets_horizontal(ax, groups, CRE_ORDER)

    save_panel(fig, "Fig8e_phyloP_raincloud")
    plt.show()


# =============================================================================
# Shared GWAS preparation for panels f and g
# =============================================================================

def build_trait_info() -> pd.DataFrame:
    trait38 = pd.read_excel(require_file(TRAIT_38_XLSX))
    meta = pd.read_csv(require_file(TRAIT_152_TSV), sep="\t")

    meta["trait_id"] = meta["filename"].str.replace(r"\.tsv\.bgz$", "", regex=True)

    abbreviation_column = next(
        (
            col
            for col in trait38.columns
            if col.lower() in {"abbreviation", "abbr", "abbrev"}
        ),
        None,
    )
    if abbreviation_column is None:
        raise ValueError(
            "No abbreviation column was found in the 38-trait workbook. "
            f"Available columns: {trait38.columns.tolist()}"
        )

    trait38["phenocode_str"] = trait38["phenocode"].astype(str).str.replace(
        r"\.0$", "", regex=True
    )
    trait38["Description_norm"] = trait38["Description"].map(norm_text)
    meta["filename_norm"] = meta["filename"].astype(str)
    meta["Description_norm"] = meta["Description"].map(norm_text)

    rows = []
    for _, row in trait38.iterrows():
        phenocode = row["phenocode_str"]
        description_norm = row["Description_norm"]

        matches = meta[
            meta["filename_norm"].str.contains(
                rf"(?:^|[-_]){re.escape(phenocode)}(?:[-_]|\.|$)",
                regex=True,
                na=False,
            )
        ].copy()

        if matches.empty and description_norm:
            matches = meta[meta["Description_norm"] == description_norm].copy()

        for _, match in matches.iterrows():
            rows.append(
                {
                    "trait_id": match["trait_id"],
                    "Description": row.get("Description", ""),
                    "Abbreviation": row.get(abbreviation_column, row.get("Description", "")),
                    "system": row.get("system", np.nan),
                }
            )

    info = (
        pd.DataFrame(rows)
        .dropna(subset=["trait_id"])
        .drop_duplicates("trait_id")
        .set_index("trait_id")
    )
    return info


def prepare_gwas_data() -> tuple[pd.DataFrame, pd.DataFrame, dict[str, str]]:
    trait_info = build_trait_info()
    tissue_colors = load_tissue_color_map()

    # The final figure treats the allergy-diagnosis-age trait as immune.
    allergy_mask = trait_info["Description"].str.contains(
        "hay fever|rhinitis|eczema", case=False, na=False
    )
    trait_info.loc[allergy_mask, "system"] = "Immune_system"

    df = pd.read_csv(require_file(GWAS_STATS))
    df = df[
        df["class"].isin(CRE_ORDER)
        & df["trait_id"].isin(trait_info.index)
        & df["tissue"].isin(TISSUE_ORDER)
        & ~df["trait_id"].isin(DROP_TRAIT_IDS)
    ].copy()

    # Keep only trait × tissue pairs represented in all four CRE classes.
    df["pair_id"] = df["trait_id"].astype(str) + "|" + df["tissue"].astype(str)
    common_pairs = (
        df.groupby("pair_id")["class"]
        .nunique()
        .loc[lambda values: values == len(CRE_ORDER)]
        .index
    )
    df = df[df["pair_id"].isin(common_pairs)].copy()

    df["P"] = df["Coefficient_P_value"].clip(lower=1e-300)
    df["neg_log10p"] = -np.log10(df["P"])
    df["nominal_pos_p05"] = (df["Coefficient"] > 0) & (df["P"] < 0.05)

    df["Description"] = df["trait_id"].map(trait_info["Description"])
    df["Abbreviation"] = df["trait_id"].map(trait_info["Abbreviation"])
    df["system"] = df["trait_id"].map(trait_info["system"])

    missing_system = df.loc[df["system"].isna(), "trait_id"].unique()
    if len(missing_system):
        raise ValueError(f"Traits missing system annotation: {missing_system.tolist()}")

    missing_system_colors = sorted(set(df["system"]) - set(SYSTEM_COLORS))
    if missing_system_colors:
        raise ValueError(f"Systems missing colors: {missing_system_colors}")

    required_tissue_color_keys = {tissue_color_key(t) for t in TISSUE_ORDER}
    missing_tissue_colors = required_tissue_color_keys - set(tissue_colors)
    if missing_tissue_colors:
        raise ValueError(
            f"Tissue colors are missing for: {sorted(missing_tissue_colors)}"
        )

    return df, trait_info, tissue_colors


# =============================================================================
# Panel f: UpSet
# =============================================================================

def build_hit_sets(df: pd.DataFrame) -> dict[str, set[tuple[str, str]]]:
    hit_sets: dict[str, set[tuple[str, str]]] = {}
    for cre in CRE_ORDER:
        sub = df[(df["class"] == cre) & df["nominal_pos_p05"]]
        hit_sets[cre] = set(
            zip(sub["trait_id"].astype(str), sub["tissue"].astype(str))
        )
    return hit_sets


def _intersection_membership_counts(
    hit_sets: dict[str, set[tuple[str, str]]],
) -> list[tuple[tuple[bool, ...], int]]:
    universe = set().union(*hit_sets.values()) if hit_sets else set()
    counts: dict[tuple[bool, ...], int] = {}

    for item in universe:
        membership = tuple(item in hit_sets[cre] for cre in CRE_ORDER)
        counts[membership] = counts.get(membership, 0) + 1

    # Match the final UpSet ordering: descending intersection size. Ties are
    # resolved deterministically by membership breadth and class pattern.
    return sorted(
        counts.items(),
        key=lambda item: (
            -item[1],
            sum(item[0]),
            tuple(-int(value) for value in item[0]),
        ),
    )


def plot_panel_f(df: pd.DataFrame) -> None:
    hit_sets = build_hit_sets(df)
    intersections = _intersection_membership_counts(hit_sets)

    memberships = [membership for membership, _ in intersections]
    counts = np.array([count for _, count in intersections], dtype=int)
    x = np.arange(len(intersections))
    y = np.arange(len(CRE_ORDER))

    singleton_colors = []
    for membership in memberships:
        present = [i for i, value in enumerate(membership) if value]
        if len(present) == 1:
            singleton_colors.append(CRE_COLORS[CRE_ORDER[present[0]]])
        else:
            singleton_colors.append("#8F8F8F")

    fig = plt.figure(figsize=(3.75, 3.15))
    gs = GridSpec(
        2,
        2,
        figure=fig,
        width_ratios=[1.0, 3.15],
        height_ratios=[1.65, 1.0],
        wspace=0.05,
        hspace=0.05,
    )

    ax_blank = fig.add_subplot(gs[0, 0])
    ax_bar = fig.add_subplot(gs[0, 1])
    ax_totals = fig.add_subplot(gs[1, 0])
    ax_matrix = fig.add_subplot(gs[1, 1], sharex=ax_bar)

    ax_blank.axis("off")

    # Intersection-size bars.
    ax_bar.bar(x, counts, color=singleton_colors, width=0.72, edgecolor="none")
    for xpos, count in zip(x, counts):
        ax_bar.text(
            xpos,
            count + max(counts.max() * 0.025, 0.18),
            str(int(count)),
            ha="center",
            va="bottom",
            fontsize=7,
        )
    ax_bar.set_ylabel("Intersection size", fontsize=8)
    ax_bar.set_xticks([])
    ax_bar.tick_params(axis="y", labelsize=7)
    ax_bar.set_ylim(0, counts.max() * 1.18 if len(counts) else 1)
    sns.despine(ax=ax_bar, bottom=True)

    # Set sizes.
    set_sizes = np.array([len(hit_sets[cre]) for cre in CRE_ORDER], dtype=int)
    ax_totals.barh(
        y,
        set_sizes,
        color=[CRE_COLORS[cre] for cre in CRE_ORDER],
        height=0.54,
        edgecolor="none",
    )
    ax_totals.invert_xaxis()
    ax_totals.set_yticks(y)
    ax_totals.set_yticklabels([])
    ax_totals.tick_params(axis="both", labelsize=7, length=0)
    ax_totals.set_ylim(-0.5, len(CRE_ORDER) - 0.5)
    ax_totals.spines["top"].set_visible(False)
    ax_totals.spines["right"].set_visible(False)
    ax_totals.spines["left"].set_visible(False)

    # Membership matrix.
    for xpos, membership in zip(x, memberships):
        ax_matrix.scatter(
            np.repeat(xpos, len(CRE_ORDER)),
            y,
            s=25,
            facecolor="#E6E6E6",
            edgecolor="none",
            zorder=1,
        )

        present = np.where(np.asarray(membership, dtype=bool))[0]
        if len(present) > 1:
            ax_matrix.plot(
                [xpos, xpos],
                [present.min(), present.max()],
                color="#8F8F8F",
                linewidth=1.1,
                zorder=2,
            )

        if len(present) == 1:
            dot_color = CRE_COLORS[CRE_ORDER[present[0]]]
        else:
            dot_color = "#8F8F8F"

        ax_matrix.scatter(
            np.repeat(xpos, len(present)),
            present,
            s=27,
            facecolor=dot_color,
            edgecolor="none",
            zorder=3,
        )

    ax_matrix.set_yticks(y)
    ax_matrix.set_yticklabels(CRE_ORDER, fontsize=7)
    ax_matrix.yaxis.tick_left()
    ax_matrix.tick_params(axis="y", length=0, pad=2)
    ax_matrix.set_xticks([])
    ax_matrix.set_xlim(-0.5, len(intersections) - 0.5)
    ax_matrix.set_ylim(-0.5, len(CRE_ORDER) - 0.5)
    for spine in ax_matrix.spines.values():
        spine.set_visible(False)

    save_panel(fig, "Fig8f_GWAS_hit_upset")
    plt.show()


# =============================================================================
# Panel g: sfCRE trait dot plot
# =============================================================================

def _ordered_trait_ids(df: pd.DataFrame, trait_info: pd.DataFrame) -> list[str]:
    description_to_ids = (
        trait_info.reset_index()
        .groupby("Description", sort=False)["trait_id"]
        .apply(list)
        .to_dict()
    )

    available = set(df["trait_id"].astype(str))
    ordered: list[str] = []
    for description in TRAIT_DESCRIPTION_ORDER:
        for trait_id in description_to_ids.get(description, []):
            trait_id = str(trait_id)
            if trait_id in available and trait_id not in ordered:
                ordered.append(trait_id)

    # Preserve any retained traits that are not covered by the explicit order.
    extras = [
        trait_id
        for trait_id in df["trait_id"].astype(str).drop_duplicates()
        if trait_id not in ordered
    ]
    return ordered + extras


def plot_panel_g(
    df: pd.DataFrame,
    trait_info: pd.DataFrame,
    tissue_colors: dict[str, str],
) -> None:
    sf = df[df["class"] == "sfCRE"].copy()
    trait_ids = _ordered_trait_ids(sf, trait_info)

    # Select the most significant record if duplicate rows exist.
    sf = (
        sf.sort_values("P")
        .drop_duplicates(["trait_id", "tissue"], keep="first")
        .copy()
    )

    trait_meta = trait_info.reindex(trait_ids).copy()
    trait_meta["Abbreviation"] = trait_meta["Abbreviation"].fillna(
        trait_meta["Description"]
    )

    y_lookup = {trait_id: i for i, trait_id in enumerate(trait_ids)}
    sf = sf[sf["trait_id"].isin(trait_ids)].copy()
    sf["y"] = sf["trait_id"].map(y_lookup).astype(float)

    rng = np.random.default_rng(123)
    sf["yj"] = sf["y"] + rng.uniform(-0.20, 0.20, len(sf))
    sf["display_tissue"] = sf["tissue"].map(tissue_color_key)
    sf["point_color"] = np.where(
        sf["nominal_pos_p05"],
        sf["display_tissue"].map(tissue_colors),
        "#D0D0D0",
    )

    fig, ax = plt.subplots(figsize=(4.55, 5.25))

    non_sig = sf[~sf["nominal_pos_p05"]]
    sig = sf[sf["nominal_pos_p05"]]

    ax.scatter(
        non_sig["neg_log10p"],
        non_sig["yj"],
        c="#D0D0D0",
        s=10,
        alpha=0.62,
        linewidths=0,
        zorder=2,
    )
    ax.scatter(
        sig["neg_log10p"],
        sig["yj"],
        c=sig["point_color"],
        s=13,
        alpha=0.95,
        linewidths=0,
        zorder=3,
    )

    threshold = -np.log10(0.05)
    ax.axvline(threshold, color="black", linestyle="--", linewidth=0.75, zorder=1)

    # Add system strip and separator lines.
    systems = trait_meta["system"].tolist()
    trans = ax.get_yaxis_transform()
    for y, system in enumerate(systems):
        ax.add_patch(
            Rectangle(
                (-0.105, y - 0.5),
                0.035,
                1.0,
                transform=trans,
                facecolor=SYSTEM_COLORS[system],
                edgecolor="none",
                clip_on=False,
            )
        )

    for y in range(len(systems) - 1):
        if systems[y] != systems[y + 1]:
            ax.axhline(y + 0.5, color="#CFCFCF", linewidth=0.55, zorder=0)

    ax.set_yticks(range(len(trait_ids)))
    ax.set_yticklabels(trait_meta["Abbreviation"].astype(str), fontsize=6.6)
    ax.set_ylim(len(trait_ids) - 0.5, -0.5)
    ax.set_xlabel(r"$-\log_{10}(P)$", fontsize=9)
    ax.set_ylabel("")
    ax.tick_params(axis="x", labelsize=8)
    ax.tick_params(axis="y", length=0, pad=7)

    finite_max = sf["neg_log10p"].replace([np.inf, -np.inf], np.nan).max()
    ax.set_xlim(0, max(4.2, min(float(finite_max) * 1.06, 6.0)))

    ax.text(
        -0.44,
        0.5,
        "sfCRE",
        transform=ax.transAxes,
        rotation=90,
        ha="center",
        va="center",
        fontsize=10,
    )
    ax.text(
        -0.34,
        1.025,
        "Trait",
        transform=ax.transAxes,
        ha="left",
        va="bottom",
        fontsize=9,
    )

    sns.despine(ax=ax)

    tissue_handles = []
    seen = set()
    for tissue in TISSUE_ORDER:
        key = tissue_color_key(tissue)
        if key in seen:
            continue
        seen.add(key)
        tissue_handles.append(
            Patch(
                facecolor=tissue_colors[key],
                edgecolor="none",
                label=TISSUE_DISPLAY.get(key, key.replace("_", " ")),
            )
        )

    system_handles = [
        Patch(
            facecolor=SYSTEM_COLORS[system],
            edgecolor="none",
            label=SYSTEM_DISPLAY[system],
        )
        for system in SYSTEM_ORDER
    ]
    non_sig_handle = Patch(
        facecolor="#D0D0D0",
        edgecolor="none",
        label=r"$P \geq 0.05$",
    )

    legend_tissue = ax.legend(
        handles=tissue_handles,
        title="Tissue",
        loc="upper left",
        bbox_to_anchor=(1.02, 1.00),
        frameon=False,
        fontsize=7,
        title_fontsize=8.5,
        borderaxespad=0,
        handlelength=1.6,
    )
    ax.add_artist(legend_tissue)

    legend_system = ax.legend(
        handles=system_handles + [non_sig_handle],
        title="System",
        loc="upper left",
        bbox_to_anchor=(1.02, 0.52),
        frameon=False,
        fontsize=7,
        title_fontsize=8.5,
        borderaxespad=0,
        handlelength=1.6,
    )

    fig.subplots_adjust(left=0.36, right=0.58, bottom=0.10, top=0.98)

    save_panel(fig, "Fig8g_sfCRE_trait_dotplot")
    plt.show()


# =============================================================================
# Entrypoint
# =============================================================================

def run_panels(panels: Iterable[str]) -> None:
    panel_set = {panel.lower() for panel in panels}
    invalid = panel_set - {"b", "d", "e", "f", "g"}
    if invalid:
        raise ValueError(f"Invalid panel(s): {sorted(invalid)}")

    if "b" in panel_set:
        plot_panel_b()
    if "d" in panel_set:
        plot_panel_d()
    if "e" in panel_set:
        plot_panel_e()

    if panel_set & {"f", "g"}:
        gwas_df, trait_info, tissue_colors = prepare_gwas_data()
        if "f" in panel_set:
            plot_panel_f(gwas_df)
        if "g" in panel_set:
            plot_panel_g(gwas_df, trait_info, tissue_colors)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--panels",
        nargs="+",
        default=["b", "d", "e", "f", "g"],
        choices=["b", "d", "e", "f", "g"],
        help="Final Fig. 8 panels to generate.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Explicitly allow overwriting existing panel files.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    ALLOW_OVERWRITE = args.force
    run_panels(args.panels)
