name: sheep-epimap
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - pip
  - snakemake-minimal
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - h5py
  - pysam
  - pybigwig
  - beautifulsoup4
  - bedtools
  - samtools
  - bcftools
  - bowtie2
  - trim-galore
  - picard
  - macs2
  - deeptools
  - sambamba
  - ucsc-bedgraphtobigwig
  - ucsc-bedclip
  - ucsc-liftover
  - meme
  - homer
  - r-base
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-ggpubr
  - r-ggrepel
  - r-optparse
  - r-patchwork
  - r-readr
  - r-reshape2
  - r-scales
  - r-spp
  - r-stringr
  - r-tidyr
  - bioconductor-complexheatmap
  - bioconductor-genomicranges
  - bioconductor-rtracklayer
  - bioconductor-edger
  - pip:
      - modisco-lite
      - tspex
