name: sheep-epimap
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - pip
  - snakemake-minimal
  - numpy
  - pandas
  - scipy
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - h5py
  - pysam
  - pybigwig
  - beautifulsoup4
  - bedtools=2.29.2
  - samtools=1.18
  - bcftools
  - bowtie2=2.5.3
  - trim-galore=0.6.5
  - picard=3.1.1
  - macs2=2.2.9.1
  - deeptools
  - sambamba
  - ucsc-bedgraphtobigwig
  - ucsc-bedclip
  - ucsc-liftover
  - meme=5.5.9
  - homer=4.11
  - r-base
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-ggpubr
  - r-ggrepel
  - r-optparse
  - r-patchwork
  - r-readr
  - r-reshape2
  - r-scales
  - r-spp
  - r-stringr
  - r-tidyr
  - bioconductor-complexheatmap
  - bioconductor-genomicranges
  - bioconductor-rtracklayer
  - bioconductor-edger=4.0.2
  - pip:
      - modisco-lite
      - tspex
